// init_config.go — generates djinn.yaml on first run from auto-detected driver.
package app

import (
	"fmt"
	"os"
	"path/filepath"
)

const configTemplate = `# Generated by djinn init — edit to customize.
driver:
  name: %s
  model: %s
mode: agent
session:
  max_turns: 30
sandbox:
  backend: ""
  level: namespace
`

// GenerateConfig writes a minimal djinn.yaml to the given directory.
func GenerateConfig(dir string, drv DetectedDriver) error {
	path := filepath.Join(dir, "djinn.yaml")

	// Don't overwrite existing config.
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("djinn.yaml already exists at %s", path)
	}

	content := fmt.Sprintf(configTemplate, drv.ACPName(), drv.DefaultModel())
	return os.WriteFile(path, []byte(content), 0644)
}

// FriendlyNoDriverError returns an actionable error message when no agent CLI
// is found on PATH and no API keys are set.
func FriendlyNoDriverError() string {
	return `no agent CLI found on PATH

Install one of:
  cursor   Cursor Agent CLI (recommended, ACP native)
             https://cursor.com/downloads
  claude   Claude Code CLI
             https://docs.anthropic.com/en/docs/claude-code
  gemini   Gemini CLI
             https://cloud.google.com/gemini
  codex    Codex CLI
             https://openai.com/codex
  ollama   Ollama (local models, privacy-first)
             https://ollama.com

Or set ANTHROPIC_API_KEY for direct Claude API access.

Then run: djinn`
}

// FriendlyDriverNotFoundError returns an actionable error when a specific
// driver binary isn't found.
func FriendlyDriverNotFoundError(driverName string) string {
	urls := map[string]string{
		"cursor": "https://cursor.com/downloads",
		"claude": "https://docs.anthropic.com/en/docs/claude-code",
		"gemini": "https://cloud.google.com/gemini",
		"codex":  "https://openai.com/codex",
		"ollama": "https://ollama.com",
	}
	url := urls[driverName]
	if url == "" {
		return fmt.Sprintf("%s driver not found. Run: djinn doctor", driverName)
	}
	return fmt.Sprintf("%s CLI not found. Install: %s\nThen run: djinn", driverName, url)
}
